
"""
Django settings for django_todo project.

Generated by 'django-admin startproject' using Django 1.11.15.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
#import env
# pip install dj_database_url, This allows django to connect to the heroku database url
# pip install psycopg2 allows django to connect to the heroku prostgres database
import dj_database_url
"""The env.py imports environment variables, Make sure to comment out in 
production mode and that the env.py is in the .gitignore file """

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

""" This should be stored as an environment variable in a env.py file like the follow below.

env.py file
import os
os.environ.setdefault("SECRET_KEY", "<Your secret key here>")
 """
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['localhost', 'all-django-projects.herokuapp.com']


# Application definition
"""If you start a new app the app name must go in here, the installed 
dependency for bootstrap forms must go here."""
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_forms_bootstrap',
    'todo',
    'accounts',
    'home',
    'posts',
    'products',
    'cart',
    'search',
    'checkout',
    'storages',  # pip install storages
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Added with pip install whitenoise
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'django_todo.urls'


"""'DIRS': [os.path.join(BASE_DIR, 'templates')], tells django that there a 
template directory outside an installed apps directory """
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # so we can serve out our media files
                'django.template.context_processors.media',
                # Added when when making context items
                'cart.context.cart_contents'
            ],
        },
    },
]

WSGI_APPLICATION = 'django_todo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases


# dj_database_url django to connect to the heroku database url pip install dj_database_url in import dj_database_url
if "DATABASE_URL" in os.environ:
    DATABASES = {'default': dj_database_url.parse(
        os.environ.get('DATABASE_URL'))}
else:
    print("Database URL not found. Using SQlite instead")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

"""This along with the backends.py allows the user to login with their email address. """
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'accounts.backends.EmailAuth'
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

AWS_S3_OBJECT_PARAMETERS = {
    'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
    'CacheControl': 'max-age=94608000',
}

AWS_STORAGE_BUCKET_NAME = 'all-django-projects'
AWS_S3_REGION_NAME = 'ap-southeast-2'
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_S2_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

# pip install boto3 pip install django-storages. This allows django to connect to AWS S3
# 'storages' must be added to ALLOWED_APP
# python manage.py collect static to send files to s3
# This is combined with the custom_storages.py file
# If fontawesome files are not working, in S3 CORS <AllowedMethod>HEAD</AllowedMethod> may have to be add.
STATICFILES_LOCATION = 'static'
STATICFILES_STORAGE = 'custom_storages.StaticStorage'


STATIC_URL = '/static/'

"""If you add a static directory in your top level project directory and e.g.
<link href="{% static 'css/styles.css' %}"> in base.html
, you have to tell django where to find that directory """
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

"""Static files are collect here for Heroku """
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# To store the media files onto S3
# This is combined with the custom_storages.py file
MEDIAFILES_LOCATION = "media"
DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


"""If using messages in views.py for user feedback, this is required"""
MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"


"""The set up required to reset your password"""
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
"""These are enviroment variables stored in env.py, your google email addess and password are
required to send an email. Make sure to import env at the top of this settings.py file.
The env.py should look similar to below.

env.py file
import os
os.environ.setdefault("EMAIL_ADDRESS", "<Your Email address here>")
os.environ.setdefault("EMAIL_PASSWORD", "<Your Email password here>")"""
EMAIL_HOST_USER = os.environ.get("EMAIL_ADDRESS")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_PASSWORD")
EMAIL_POST = 587

STRIPE_PUBLISHABLE = os.environ.get('STRIPE_PUBLISHABLE')
STRIPE_SECRET = os.environ.get('STRIPE_SECRET')
